### ISSUE TITLE
Pointers on unit testing fastify plugin

### ISSUE THREAD

**Issue by emilbayes** [fastify/fastify-plugin#33]
Hi!

Any pointers as to unit test individual fastify plugins and on integration testing between plugins? `fastify.inject` is fine for HTTP, and I can decouple most plugins from fastify itself, but sometimes you need specific integrations that are error prone setting up by hand, and where you'd like to actually test it in fastify.

**Comment by delvedor** [comment]
Hi! Thank you for checking out Fastify!
Can you show us an example of what you are trying to test?

If you want to see the test of Fastify plugins that depends on other Fastify plugins you can see [fastify-http-proxy](https://github.com/fastify/fastify-http-proxy). Otherwise you can checkout [fastify-static](https://github.com/fastify/fastify-static) to see how we test the integration with other plugins, such as [fastify-compress](https://github.com/fastify/fastify-compress).
